# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: cimg/node:19.0.1

    steps:
      - checkout
      - run:
          name: node Install
          command: node --version

      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "vbikavithak@users.noreply.github.com"
            git config --global user.name "vbikavithak"
            echo "machine github.com login vbikavithak password $GITHUB_TOKEN" > ~/.netrc
            GIT_USER=vbikavithak yarn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master
